# Generated by Django 2.1.7 on 2019-03-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='done',
            field=models.TextField(default='y'),
            preserve_default=False,
        ),
    ]
