# Generated by Django 2.1.7 on 2019-03-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190314_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='done',
            field=models.TextField(default='n'),
        ),
    ]
