# Generated by Django 2.1.7 on 2019-03-13 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20190314_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='done',
        ),
    ]
